### ISSUE TITLE
Gallery page

### ISSUE THREAD

**Issue by Marcerisson** [42-2/42-2.github.io#2]
add a slider for photos (use temporary photos until we have good looking screenshots)

**Comment by WrongPasswd** [comment]
copied/pasted a thing that  would look good if it worked
Home button is highlighted in gray because of whatever thing in the copied css, and the pictures appear and disappear after 2 second... will debug

**Comment by Marcerisson** [comment]
https://getbootstrap.com/docs/4.0/components/carousel/
